;***************************************
;
;       PROGRAMA MONITOR NESTOR
;           NOVA ELETRONICA
;    SAO PAULO S.P. 01/84 MSCS/JRP
;            Digitado por
;          Fábio Belavenuto
;            em 27/11/2012
;
;***************************************

;***************************************
;
; Endereços do monitor para serem usados
; em softwares utilitários incluindo
; este arquivo
;
;***************************************

RESET		= 0000h
VARR		= 0090h
REST		= 009Ch
TEMPO		= 0091h
AJCOL		= 00DBh
AJTEC		= 00D8h
DISPLAY		= 016Eh
FORMAT		= 0186h
TOM			= 0941h
