SELECT PUBLICACOES.NO_PUBLICACAO,
       EDICOES.AN_EDICAO, EDICOES.NU_EDICAO,
       CONTEUDO.NU_PAGINA, CONTEUDO.TX_CONTEUDO
FROM PUBLICACOES,EDICOES,CONTEUDO
WHERE PUBLICACOES.CD_PUBLICACAO = EDICOES.CD_PUBLICACAO
AND   EDICOES.CD_EDICAO = CONTEUDO.CD_EDICAO
AND   upper(CONTEUDO.TX_CONTEUDO) LIKE '%USB%'
/*ORDER BY CONTEUDO.TX_CONTEUDO*/
ORDER BY EDICOES.NU_EDICAO,CONTEUDO.NU_PAGINA