object Frame1: TFrame1
  Left = 0
  Top = 0
  Width = 334
  Height = 43
  TabOrder = 0
  object GroupBox1: TGroupBox
    Left = 0
    Top = 0
    Width = 334
    Height = 43
    Align = alClient
    Caption = 'GroupBox1'
    TabOrder = 0
    object ScrollBar1: TScrollBar
      Left = 2
      Top = 18
      Width = 330
      Height = 21
      Align = alTop
      PageSize = 0
      TabOrder = 0
    end
  end
end
